title: Oleg Parashchenko, fullstack developer in lead roles. ML, NLP, AWS, Terraform, TypeScript, Python
email: olpa@uucode.com
description: >-
  advocating my software, tools and thoughts; sharing insights
baseurl: ""
url: ""
twitter_username: olparko
github_username:  olpa
repository: olpa/olpa.github.io

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: myarchive
  permalinks:
    category: '/blog/category/:name/'
