title: Oleg Parashchenko, fullstack developer in lead roles. ML, NLP, AWS, Terraform, TypeScript, Python
email: olpa@uucode.com
description: >-
  advocating my software, tools and thoughts; sharing insights
baseurl: ""
url: ""
twitter_username: olparko
github_username:  olpa

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: myarchive
  permalinks:
    category: '/blog/category/:name.html'
